# Generated by Django 3.2 on 2021-04-12 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='<h1>Empty Article !!!</h1>'),
        ),
    ]
